import type { Property, Conversation, Application, Lease, MaintenanceRequest } from './types';

export const properties: Property[] = [
  {
    id: 'prop1',
    title: 'Modern Villa in Beverly Hills',
    price: 3500000,
    address: '123 Luxury Lane',
    city: 'Beverly Hills',
    state: 'CA',
    zip: '90210',
    bedrooms: 5,
    bathrooms: 6,
    sqft: 6000,
    type: 'House',
    status: 'For Sale',
    description: 'A stunning modern villa with breathtaking views, a home theater, and an infinity pool. Experience luxury living at its finest.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    features: ['Infinity Pool', 'Home Theater', 'Gourmet Kitchen', '3-Car Garage', 'Smart Home System'],
    agent: { name: 'Jane Doe', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: '2023-10-26',
    virtualTourUrl: '#',
    priceHistory: [ { date: '2023-01-01', price: 3200000, label: 'Jan' }, { date: '2023-04-01', price: 3350000, label: 'Apr' }, { date: '2023-07-01', price: 3450000, label: 'Jul' }, { date: '2023-10-01', price: 3500000, label: 'Oct' } ],
    floodRisk: 'Low'
  },
  {
    id: 'prop2',
    title: 'Cozy Downtown Apartment',
    price: 3200,
    address: '456 Urban St, Apt 12B',
    city: 'San Francisco',
    state: 'CA',
    zip: '94105',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    type: 'Apartment',
    status: 'Rented',
    description: 'A chic and cozy apartment in the heart of the city, featuring modern amenities and floor-to-ceiling windows with city views.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    features: ['City View', 'Modern Kitchen', 'Fitness Center', '24/7 Security'],
    agent: { name: 'John Smith', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: '2023-11-05',
    priceHistory: [ { date: '2023-02-01', price: 720000, label: 'Feb' }, { date: '2023-05-01', price: 730000, label: 'May' }, { date: '2023-08-01', price: 740000, label: 'Aug' }, { date: '2023-11-01', price: 750000, label: 'Nov' } ],
    floodRisk: 'Medium'
  },
  {
    id: 'prop3',
    title: 'Suburban Family Home',
    price: 980000,
    address: '789 Maple Ave',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3500,
    type: 'House',
    status: 'For Sale',
    description: 'Spacious family home in a quiet suburban neighborhood. Large backyard, great schools nearby, and a newly renovated kitchen.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    features: ['Large Backyard', 'Renovated Kitchen', 'Community Pool', 'Fireplace'],
    agent: { name: 'Emily White', avatar: 'https://placehold.co/100x100.png' },
    isVerified: false,
    postedDate: '2023-11-15',
    priceHistory: [ { date: '2023-03-01', price: 950000, label: 'Mar' }, { date: '2023-06-01', price: 965000, label: 'Jun' }, { date: '2023-09-01', price: 975000, label: 'Sep' }, { date: '2023-11-01', price: 980000, label: 'Nov' } ],
    floodRisk: 'High'
  },
  {
    id: 'prop4',
    title: 'Rustic Lakeside Cabin',
    price: 550000,
    address: '101 Forest Rd',
    city: 'Lake Tahoe',
    state: 'CA',
    zip: '96145',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    type: 'House',
    status: 'For Sale',
    description: 'Charming cabin with lake access. Perfect for a vacation home or a peaceful primary residence. Features a large deck and stone fireplace.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    features: ['Lake Access', 'Large Deck', 'Stone Fireplace', 'Wooded Lot'],
    agent: { name: 'Michael Brown', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: '2023-11-20',
    priceHistory: [ { date: '2023-01-01', price: 520000, label: 'Jan' }, { date: '2023-04-01', price: 530000, label: 'Apr' }, { date: '2023-07-01', price: 540000, label: 'Jul' }, { date: '2023-10-01', price: 550000, label: 'Oct' } ],
    floodRisk: 'None'
  },
  {
    id: 'prop5',
    title: 'Miami Beachfront Condo',
    price: 4500,
    address: '25 Ocean Drive',
    city: 'Miami',
    state: 'FL',
    zip: '33139',
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2200,
    type: 'Condo',
    status: 'Rented',
    description: 'Luxurious condo with direct beach access and panoramic ocean views. State-of-the-art amenities.',
    images: ['https://placehold.co/800x600.png'],
    features: ['Oceanfront', 'Rooftop Pool', 'Valet Parking', 'Gym'],
    agent: { name: 'Sophia Garcia', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: '2023-11-22',
    priceHistory: [ { date: '2023-01-01', price: 1100000, label: 'Jan' }, { date: '2023-05-01', price: 1150000, label: 'May' }, { date: '2023-09-01', price: 1200000, label: 'Sep' } ],
    floodRisk: 'Medium'
  },
  {
    id: 'prop6',
    title: 'Denver Mountain View House',
    price: 850000,
    address: '555 Peak Lane',
    city: 'Denver',
    state: 'CO',
    zip: '80202',
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3200,
    type: 'House',
    status: 'For Sale',
    description: 'Modern home with stunning Rocky Mountain views. Open floor plan and high-end finishes throughout.',
    images: ['https://placehold.co/800x600.png'],
    features: ['Mountain Views', 'Open Concept', 'Heated Floors', '2-Car Garage'],
    agent: { name: 'David Miller', avatar: 'https://placehold.co/100x100.png' },
    isVerified: false,
    postedDate: '2023-11-18',
    priceHistory: [ { date: '2023-02-01', price: 820000, label: 'Feb' }, { date: '2023-06-01', price: 835000, label: 'Jun' }, { date: '2023-10-01', price: 850000, label: 'Oct' } ],
    floodRisk: 'Low'
  },
  {
    id: 'prop7',
    title: 'Historic Boston Brownstone',
    price: 2100000,
    address: '12 Beacon St',
    city: 'Boston',
    state: 'MA',
    zip: '02108',
    bedrooms: 4,
    bathrooms: 5,
    sqft: 4000,
    type: 'House',
    status: 'For Sale',
    description: 'A piece of history in Beacon Hill. This brownstone combines classic charm with modern updates.',
    images: ['https://placehold.co/800x600.png'],
    features: ['Historic District', 'Rooftop Terrace', 'Original Woodwork', 'Wine Cellar'],
    agent: { name: 'Olivia Chen', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: '2023-11-12',
    priceHistory: [ { date: '2023-01-01', price: 2000000, label: 'Jan' }, { date: '2023-06-01', price: 2050000, label: 'Jun' }, { date: '2023-11-01', price: 2100000, label: 'Nov' } ],
    floodRisk: 'Low'
  },
  {
    id: 'prop8',
    title: 'Chicago Loft with Skyline View',
    price: 680000,
    address: '99 Wicker Park Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60622',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1500,
    type: 'Condo',
    status: 'For Sale',
    description: 'Stunning loft in a trendy neighborhood with exposed brick and panoramic city views.',
    images: ['https://placehold.co/800x600.png'],
    features: ['Exposed Brick', 'High Ceilings', 'Private Balcony', 'Rooftop Deck'],
    agent: { name: 'Ethan Williams', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: '2023-11-10',
    priceHistory: [ { date: '2023-03-01', price: 650000, label: 'Mar' }, { date: '2023-07-01', price: 670000, label: 'Jul' }, { date: '2023-11-01', price: 680000, label: 'Nov' } ],
    floodRisk: 'Low'
  },
  {
    id: 'prop9',
    title: 'Seattle Waterfront House',
    price: 1800000,
    address: '42 Puget Sound Rd',
    city: 'Seattle',
    state: 'WA',
    zip: '98101',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3800,
    type: 'House',
    status: 'For Sale',
    description: 'Beautiful waterfront property with private dock and stunning views of Puget Sound.',
    images: ['https://placehold.co/800x600.png'],
    features: ['Waterfront', 'Private Dock', 'Floor-to-ceiling windows', 'Hot Tub'],
    agent: { name: 'Isabella Johnson', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: '2023-11-08',
    priceHistory: [ { date: '2023-02-01', price: 1750000, label: 'Feb' }, { date: '2023-06-01', price: 1780000, label: 'Jun' }, { date: '2023-10-01', price: 1800000, label: 'Oct' } ],
    floodRisk: 'Medium'
  },
  {
    id: 'prop10',
    title: 'Phoenix Desert Oasis',
    price: 950000,
    address: '7 Cactus Lane',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85001',
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4500,
    type: 'House',
    status: 'For Sale',
    description: 'Spacious home with a resort-style backyard, pool, and outdoor kitchen.',
    images: ['https://placehold.co/800x600.png'],
    features: ['Swimming Pool', 'Outdoor Kitchen', 'Desert Landscaping', 'Solar Panels'],
    agent: { name: 'Lucas Hernandez', avatar: 'https://placehold.co/100x100.png' },
    isVerified: false,
    postedDate: '2023-11-01',
    priceHistory: [ { date: '2023-04-01', price: 920000, label: 'Apr' }, { date: '2023-08-01', price: 935000, label: 'Aug' }, { date: '2023-11-01', price: 950000, label: 'Nov' } ],
    floodRisk: 'Low'
  },
  ...Array.from({ length: 34 }, (_, i) => ({
    id: `prop${11 + i}`,
    title: 'Spacious Family Home',
    price: 800000 + i * 10000,
    address: `${100 + i} Oak Street`,
    city: 'Columbus',
    state: 'OH',
    zip: '43215',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2800 + i * 50,
    type: 'House' as Property['type'],
    status: 'For Sale' as 'For Sale' | 'For Rent' | 'Sold' | 'Rented',
    description: 'A beautiful and spacious home perfect for families, located in a friendly neighborhood.',
    images: [`https://placehold.co/800x600.png`],
    features: ['Large Yard', '2-Car Garage', 'Modern Kitchen', 'Community Park'],
    agent: { name: 'Agent Smith', avatar: 'https://placehold.co/100x100.png' },
    isVerified: i % 2 === 0,
    postedDate: `2023-10-${(i % 30) + 1}`,
    priceHistory: [ { date: '2023-01-01', price: 780000 + i * 10000, label: 'Jan' }, { date: '2023-06-01', price: 790000 + i * 10000, label: 'Jun' } ],
    floodRisk: 'Low' as 'Low' | 'Medium' | 'High' | 'None'
  })),
  ...Array.from({ length: 34 }, (_, i) => ({
    id: `rent${1 + i}`,
    title: `Modern Downtown Loft`,
    price: 2500 + i * 100,
    address: `${200 + i} High Street, Apt ${300 + i}`,
    city: 'New York',
    state: 'NY',
    zip: '10001',
    bedrooms: 1 + (i % 3),
    bathrooms: 1 + (i % 2),
    sqft: 800 + i * 20,
    type: 'Apartment' as Property['type'],
    status: i % 4 === 0 ? 'Rented' : 'For Rent' as 'For Sale' | 'For Rent' | 'Sold' | 'Rented',
    description: 'Stylish apartment for rent in a prime downtown location, with great amenities.',
    images: [`https://placehold.co/800x600.png`],
    features: ['Gym Access', 'Rooftop Terrace', 'In-unit Laundry', 'Concierge'],
    agent: { name: 'Rental Group', avatar: 'https://placehold.co/100x100.png' },
    isVerified: i % 3 === 0,
    postedDate: `2023-11-${(i % 30) + 1}`,
    priceHistory: [],
    floodRisk: 'Low' as 'Low' | 'Medium' | 'High' | 'None'
  })),
  ...Array.from({ length: 34 }, (_, i) => ({
    id: `sr${i + 1}`,
    title: `Cozy Single Room ${i + 1}`,
    price: 600 + i * 20,
    address: `${300 + i} College Ave`,
    city: 'Student City',
    state: 'MA',
    zip: '02140',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 250 + i * 5,
    type: 'Single Room',
    status: 'For Rent',
    description: 'A comfortable and affordable single room, perfect for students or young professionals.',
    images: [`https://placehold.co/800x600.png`],
    features: ['Shared Kitchen', 'All Utilities Included', 'Furnished', 'Close to Campus'],
    agent: { name: 'Campus Rentals', avatar: 'https://placehold.co/100x100.png' },
    isVerified: i % 3 === 0,
    postedDate: `2023-11-${(i % 30) + 1}`,
    priceHistory: [],
    floodRisk: 'Low'
  })),
  ...Array.from({ length: 34 }, (_, i) => ({
    id: `rp${i + 1}`,
    title: `Spacious Room & Parlor Apt ${i + 1}`,
    price: 1200 + i * 50,
    address: `${400 + i} Family Circle`,
    city: 'Metroville',
    state: 'GA',
    zip: '30303',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600 + i * 10,
    type: 'R&P Apart',
    status: 'For Rent',
    description: 'A well-laid-out room and parlor apartment with a separate living area.',
    images: [`https://placehold.co/800x600.png`],
    features: ['Separate Living Room', 'Balcony', 'Gated Community', 'Parking Space'],
    agent: { name: 'City Apartments', avatar: 'https://placehold.co/100x100.png' },
    isVerified: i % 2 === 0,
    postedDate: `2023-11-${(i % 30) + 1}`,
    priceHistory: [],
    floodRisk: 'Medium'
  })),
  ...Array.from({ length: 34 }, (_, i) => ({
    id: `sa${i + 1}`,
    title: `Modern Self-Contained Apt ${i + 1}`,
    price: 1800 + i * 75,
    address: `${500 + i} Independence Way`,
    city: 'Liberty Town',
    state: 'PA',
    zip: '19104',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750 + i * 15,
    type: 'Self Apart',
    status: 'For Rent',
    description: 'A fully self-contained apartment with a private kitchen and bathroom.',
    images: [`https://placehold.co/800x600.png`],
    features: ['Private Kitchen', 'Modern Bathroom', 'Washer/Dryer', 'High-Speed Internet'],
    agent: { name: 'Prestige Living', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: `2023-11-${(i % 30) + 1}`,
    priceHistory: [],
    floodRisk: 'Low'
  })),
  ...Array.from({ length: 34 }, (_, i) => ({
    id: `os${i + 1}`,
    title: `Prime Downtown Office Space ${i + 1}`,
    price: 5000 + i * 200,
    address: `${10 + i} Commerce Plaza`,
    city: 'Business Bay',
    state: 'NY',
    zip: '10005',
    bedrooms: 0,
    bathrooms: 0,
    sqft: 1000 + i * 100,
    type: 'Office Space',
    status: 'For Rent',
    description: 'A professional office space in a high-rise building with great amenities.',
    images: [`https://placehold.co/800x600.png`],
    features: ['Conference Rooms', 'Reception Service', 'High-Speed Internet', 'Parking Garage'],
    agent: { name: 'Corporate Realty', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: `2023-10-${(i % 30) + 1}`,
    priceHistory: [],
    floodRisk: 'Low'
  })),
  ...Array.from({ length: 34 }, (_, i) => ({
    id: `wh${i + 1}`,
    title: `Large Industrial Warehouse ${i + 1}`,
    price: 10000 + i * 500,
    address: `${1 + i} Logistics Drive`,
    city: 'Industry City',
    state: 'NJ',
    zip: '07302',
    bedrooms: 0,
    bathrooms: 0,
    sqft: 20000 + i * 1000,
    type: 'Warehouse',
    status: 'For Rent',
    description: 'A massive warehouse space with high ceilings and multiple loading docks.',
    images: [`https://placehold.co/800x600.png`],
    features: ['Loading Docks', '30ft Ceilings', 'Office Space Included', 'Secure Yard'],
    agent: { name: 'Industrial Properties', avatar: 'https://placehold.co/100x100.png' },
    isVerified: i % 2 === 0,
    postedDate: `2023-10-${(i % 30) + 1}`,
    priceHistory: [],
    floodRisk: 'Medium'
  })),
  ...Array.from({ length: 34 }, (_, i) => ({
    id: `sh${i + 1}`,
    title: `Retail Shop on Main Street ${i + 1}`,
    price: 3500 + i * 150,
    address: `${1000 + i} Main St`,
    city: 'Commerceville',
    state: 'CA',
    zip: '90212',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 1200 + i * 50,
    type: 'Shop',
    status: 'For Rent',
    description: 'A retail shop with high foot traffic and excellent window display opportunities.',
    images: [`https://placehold.co/800x600.png`],
    features: ['High Foot Traffic', 'Large Windows', 'Stock Room', 'Street Parking'],
    agent: { name: 'Retail Spaces Inc.', avatar: 'https://placehold.co/100x100.png' },
    isVerified: true,
    postedDate: `2023-10-${(i % 30) + 1}`,
    priceHistory: [],
    floodRisk: 'Low'
  })),
  ...Array.from({ length: 34 }, (_, i) => ({
    id: `ld${i + 1}`,
    title: `Residential Land Plot ${i + 1}`,
    price: 250000 + i * 10000,
    address: `Lot ${10 + i}, Greenfield Estates`,
    city: 'Rural County',
    state: 'TX',
    zip: '78610',
    bedrooms: 0,
    bathrooms: 0,
    sqft: 43560 + i * 1000, // 1 acre +
    type: 'Land',
    status: 'For Sale',
    description: 'A beautiful plot of land ready for you to build your dream home.',
    images: [`https://placehold.co/800x600.png`],
    features: ['Utilities Available', 'Paved Road Access', 'No HOA', 'Zoned Residential'],
    agent: { name: 'Landmark Realty', avatar: 'https://placehold.co/100x100.png' },
    isVerified: i % 4 === 0,
    postedDate: `2023-09-${(i % 30) + 1}`,
    priceHistory: [],
    floodRisk: 'None'
  })),
];


export const conversations: Conversation[] = [
  {
    id: 1,
    name: "Jane Doe (Agent)",
    property: "Modern Villa",
    avatar: "https://placehold.co/100x100.png",
    messages: [
      { from: "Jane Doe (Agent)", text: "Hi John, I have some great news about the Modern Villa!", time: "10:00 AM", read: true },
      { from: "John Doe", text: "That's exciting! What's the update?", time: "10:01 AM" },
      { from: "Jane Doe (Agent)", text: "The seller has accepted your offer! Congratulations!", time: "10:02 AM", read: true },
      { from: "John Doe", text: "Wow, that's fantastic! Thanks for all your help, Jane.", time: "10:05 AM" },
    ]
  },
  {
    id: 2,
    name: "Tenant (456 Urban St)",
    property: "Cozy Downtown Apartment",
    avatar: "https://placehold.co/100x100.png",
    messages: [
        { from: "Tenant (456 Urban St)", text: "Hi John, the sink in the kitchen is leaking. Can you please take a look?", time: "Yesterday", read: true },
        { from: "John Doe", text: "Oh no, sorry to hear that. I'll get a plumber to come over tomorrow morning. Is that okay?", time: "Yesterday" },
        { from: "Tenant (456 Urban St)", text: "Yes, that works perfectly. Thank you!", time: "Yesterday", read: true },
    ]
  },
    {
    id: 3,
    name: "Michael Brown (Agent)",
    property: "Rustic Lakeside Cabin",
    avatar: "https://placehold.co/100x100.png",
    messages: [
      { from: "Michael Brown (Agent)", text: "Following up on the Rustic Lakeside Cabin - are you still interested in scheduling a viewing?", time: "3 days ago", read: false },
    ]
  },
];

const rentalProperty = properties.find(p => p.status === 'For Rent');
const forSaleProperty = properties.find(p => p.status === 'For Sale');


export const applications: Application[] = [
    {
        id: 'app1',
        propertyId: rentalProperty?.id || 'rent1',
        propertyTitle: rentalProperty?.title || 'Modern Downtown Loft',
        propertyImage: rentalProperty?.images[0] || 'https://placehold.co/800x600.png',
        status: 'Approved',
        dateSubmitted: '2023-11-15',
        type: 'Rental',
    },
    {
        id: 'app2',
        propertyId: forSaleProperty?.id || 'prop2',
        propertyTitle: forSaleProperty?.title || 'Cozy Downtown Apartment',
        propertyImage: forSaleProperty?.images[0] || 'https://placehold.co/800x600.png',
        status: 'Under Review',
        dateSubmitted: '2023-11-20',
        type: 'Offer',
    },
    {
        id: 'app3',
        propertyId: 'rent3',
        propertyTitle: 'Modern Downtown Loft',
        propertyImage: 'https://placehold.co/800x600.png',
        status: 'Submitted',
        dateSubmitted: '2023-11-22',
        type: 'Rental',
    },
     {
        id: 'app4',
        propertyId: 'prop7',
        propertyTitle: 'Historic Boston Brownstone',
        propertyImage: 'https://placehold.co/800x600.png',
        status: 'Rejected',
        dateSubmitted: '2023-10-30',
        type: 'Offer',
    },
]

export const leases: Lease[] = [
    { id: 'lease1', propertyId: 'prop2', propertyTitle: 'Cozy Downtown Apartment', tenantName: 'Alice Johnson', startDate: '2023-08-01', endDate: '2024-07-31', rentAmount: 3200, status: 'Active' },
    { id: 'lease2', propertyId: 'prop5', propertyTitle: 'Miami Beachfront Condo', tenantName: 'Bob Williams', startDate: '2023-06-15', endDate: '2024-06-14', rentAmount: 4500, status: 'Active' },
    { id: 'lease3', propertyId: 'rent4', propertyTitle: 'Modern Downtown Loft', tenantName: 'Charlie Brown', startDate: '2023-09-01', endDate: '2024-08-31', rentAmount: 2800, status: 'Active' },
    { id: 'lease4', propertyId: 'rent8', propertyTitle: 'Modern Downtown Loft', tenantName: 'Diana Prince', startDate: '2022-12-01', endDate: '2023-11-30', rentAmount: 3100, status: 'Expired' },
];

export const maintenanceRequests: MaintenanceRequest[] = [
    { id: 'maint1', propertyId: 'prop2', propertyTitle: 'Cozy Downtown Apartment', tenantName: 'Alice Johnson', dateSubmitted: '2023-11-28', description: "The kitchen sink is clogged and water is not draining properly.", category: 'Plumbing', priority: 'High', status: 'Pending' },
    { id: 'maint2', propertyId: 'prop5', propertyTitle: 'Miami Beachfront Condo', tenantName: 'Bob Williams', dateSubmitted: '2023-11-25', description: "The AC unit in the master bedroom is making a loud rattling noise.", category: 'HVAC', priority: 'Medium', status: 'In Progress' },
    { id: 'maint3', propertyId: 'rent4', propertyTitle: 'Modern Downtown Loft', tenantName: 'Charlie Brown', dateSubmitted: '2023-11-22', description: "A light fixture in the hallway has burned out. I can't reach it to change the bulb.", category: 'Electrical', priority: 'Low', status: 'Completed' },
    { id: 'maint4', propertyId: 'prop2', propertyTitle: 'Cozy Downtown Apartment', tenantName: 'Alice Johnson', dateSubmitted: '2023-11-20', description: "The main door lock is sticking and it's very difficult to turn the key.", category: 'Structural', priority: 'High', status: 'Completed' },
    { id: 'maint5', propertyId: 'prop5', propertyTitle: 'Miami Beachfront Condo', tenantName: 'Bob Williams', dateSubmitted: '2023-11-18', description: "No hot water in the guest bathroom. The rest of the apartment is fine.", category: 'Plumbing', priority: 'Emergency', status: 'Pending' },
];